### PR TITLE
1.9.0

### PR DESCRIPTION
**Pull request by GamakCZ**
protocol update

### CODE REVIEW

**Comment by lukeeey** [comment]
Have you even tested this

**Comment by GamakCZ** [comment]
yes, but not with gomint, tommorow I'll test it

**Comment by lukeeey** [comment]
I heard that there is changes in the login packet or some hacks needed to make 1.9 work.

**Comment by GamakCZ** [comment]
Doesn't work. Try #59

**Comment by GamakCZ** [comment]
`java.lang.IllegalArgumentException: Cannot read more bytes than are available
        at io.gomint.jraknet.PacketBuffer.ensureRemaining(PacketBuffer.java:78) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.jraknet.PacketBuffer.readLShort(PacketBuffer.java:88) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.network.protocol.PacketResourcePacksInfo.deserialize(PacketResourcePacksInfo.java:82) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.network.DownstreamConnection.handlePacket(DownstreamConnection.java:474) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.network.DownstreamConnection.updateIncoming(DownstreamConnection.java:260) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:762) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_191]
        at io.gomint.proxprox.Bootstrap.main(Bootstrap.java:68) [ProxProx.jar:1.0-SNAPSHOT-"dd04f3c"]`

**Pull request merged**
